---

- name: download homebrew uninstall.sh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh
    dest: /tmp/homebrew-uninstall.sh
    owner: root
    group: "{{ lookup('ansible.builtin.pipe', 'id -gn root') }}"
    mode: 0755
  become: true

- name: download homebrew install.sh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: /tmp/homebrew-install.sh
    owner: root
    group: "{{ lookup('ansible.builtin.pipe', 'id -gn root') }}"
    mode: 0755
  become: true

- name: distribution block
  block:

    - name: include distribution tasks
      ansible.builtin.include_tasks:
        file: "{{ ansible_distribution | lower }}.yml"

  rescue:

    - name: not implemented
      ansible.builtin.debug:
        msg: |
          distribution {{ ansible_distribution }} not implemented

# - name: brew doctor
#   ansible.builtin.command:
#     cmd: brew doctor
#   register: doctor
#   ignore_errors: true  # needs to potentially fail
#   environment:
#     PATH: /home/linuxbrew/.linuxbrew/bin:"{{ lookup('ansible.builtin.env', 'PATH') }}"

# - name: brew fix
#   ansible.builtin.shell:
#     cmd: |
#       rm -rf /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core;
#       brew tap homebrew/core
#   when:
#     - "'Warning: Homebrew/homebrew-core was not tapped properly! Run:' in doctor.stderr"
#     - "'rm -rf \"/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core\"' in doctor.stderr"
#     - "'brew tap homebrew/core' in doctor.stderr"
#   environment:
#     PATH: /home/linuxbrew/.linuxbrew/bin:"{{ lookup('ansible.builtin.env', 'PATH') }}"
