- name: install prereqs
  ansible.builtin.apt:
    update_cache: true
    state: present
    package:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  become: true

- name: kernel modules
  community.general.modprobe:
    state: present
    name: "{{ module }}"
  loop:
    - kvm
    - kvm_intel
  loop_control:
    loop_var: module
  become: true
  when: not CI

- name: add docker gpg key
  ansible.builtin.apt_key:
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg
  become: true

- name: add docker apt repo
  ansible.builtin.apt_repository:
    state: present
    filename: docker
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
  become: true

- name: install docker
  ansible.builtin.apt:
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
  become: true
