- name: install prereqs
  ansible.builtin.apt:
    update_cache: true
    state: present
    package:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  become: true

- name: kernel modules
  community.general.modprobe:
    state: present
    name: "{{ module }}"
  loop:
    - kvm
    - kvm_intel
  loop_control:
    loop_var: module
  become: true
