---
- name: site
  hosts: localhost
  connection: local
  gather_facts: true
  become: false

  vars:

    CI: "{{ lookup('ansible.builtin.env', 'CI') | default(false, true) | bool }}"

  tasks:

    - name: ping
      ansible.builtin.ping:

    - name: ubuntu
      ansible.builtin.include_role:
        name: ubuntu
      when: ansible_distribution == "Ubuntu"

    - name: macos
      ansible.builtin.include_role:
        name: macos
      when: ansible_distribution == "MacOSX"

    - name: docker
      ansible.builtin.include_role:
        name: docker

    - name: homebrew
      ansible.builtin.include_role:
        name: homebrew
        apply:
          tags:
            - brew
            - homebrew
      tags:
        - always
      when: not CI
