---
- name: site
  hosts: localhost
  connection: local
  gather_facts: true
  become: false

  vars:

    CI: "{{ lookup('ansible.builtin.env', 'CI') | default(false, true) | bool }}"

  tasks:

    - name: ping
      ansible.builtin.ping:

    - name: ubuntu
      ansible.builtin.include_role:
        name: ubuntu
      when: ansible_distribution == "Ubuntu"

    - name: docker
      ansible.builtin.include_role:
        name: docker
