- name: fetch nix tarball
  ansible.builtin.get_url:
    url: "{{ tarball.url }}"
    checksum: "sha256:{{ tarball.sha256 }}"
    dest: /tmp

- name: create nix directory
  ansible.builtin.file:
    state: directory
    dest: /tmp/{{ tarball.dirname }}

- name: unarchive nix tarball
  ansible.builtin.command:
    cmd: tar -xJf /tmp/{{ tarball.basename }} -C /tmp/{{ tarball.dirname }}
    creates: /tmp/{{ tarball.dirname }}/{{ tarball.extdir }}/install
