name: ansible

on:
  push:
    branches:
      - main

jobs:

  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: set up python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install --requirement requirements.txt

      - name: ansible
        working-directory: ansible
        run: |
          ansible -i inventory.yml -m ping all
          ansible-playbook -i inventory.yml site.yml -v
