name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: pre-commit
        uses: pre-commit/action@v2.0.3

      - name: slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: ci
          SLACK_TITLE: ${{ github.repository }}
          SLACK_ICON_EMOJI: ":ship:"
          SLACK_COLOR: ${{ job.status }}
          SLACK_FOOTER: ${{ runner.name }}
